//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iApprove.LangResource {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppData {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppData() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("iApprove.LangResource.AppData", typeof(AppData).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string titleLoginPage {
            get {
                return ResourceManager.GetString("titleLoginPage", resourceCulture);
            }
        }
        
        internal static string iApproveHeaderText {
            get {
                return ResourceManager.GetString("iApproveHeaderText", resourceCulture);
            }
        }
        
        internal static string iApproveSubText {
            get {
                return ResourceManager.GetString("iApproveSubText", resourceCulture);
            }
        }
        
        internal static string userNameText {
            get {
                return ResourceManager.GetString("userNameText", resourceCulture);
            }
        }
        
        internal static string passwordText {
            get {
                return ResourceManager.GetString("passwordText", resourceCulture);
            }
        }
        
        internal static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        internal static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        internal static string titleHomePage {
            get {
                return ResourceManager.GetString("titleHomePage", resourceCulture);
            }
        }
        
        internal static string titlePendingRequestsPage {
            get {
                return ResourceManager.GetString("titlePendingRequestsPage", resourceCulture);
            }
        }
        
        internal static string selectReasonToDeny {
            get {
                return ResourceManager.GetString("selectReasonToDeny", resourceCulture);
            }
        }
        
        internal static string txtDenyReason {
            get {
                return ResourceManager.GetString("txtDenyReason", resourceCulture);
            }
        }
        
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
    }
}
